import pygame
import sys

# Pygame başlatma
pygame.init()

# Pencere boyutları
width, height = 800, 600

# Renkler
black = (0, 0, 0)
white = (255, 255, 255)

# Pencere oluşturma
window = pygame.display.set_mode((width, height))
pygame.display.set_caption("Clicker Game")

# Font ve text objesi oluşturma
font = pygame.font.Font(None, 36)
click_count = 0

# Oyun döngüsü
while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit()
        elif event.type == pygame.MOUSEBUTTONDOWN:
            if event.button == 1:  # Sol tıklama
                click_count += 1

    # Pencereyi temizle
    window.fill(white)

    # Tıklama sayısını göster
    text = font.render(f"Click Count: {click_count}", True, black)
    window.blit(text, (10, 10))

    # Pencereyi güncelle
    pygame.display.flip()

    # FPS sınırlama
    pygame.time.Clock().tick(60)
